### ISSUE TITLE
[cmake_installer] no new uploads on bintray

### ISSUE THREAD

**Issue by tonka3000** [conan-community/community#187]
Hey,

version 3.14.3 was added 5 days add to the conan-cmake-installer repo. The build pass but there is no package on bintray (conan-center or conan-community).

Is that a bug or intended, because it is on the master branch? Or is the no automatic upload for that repo?

Greetings  
Tonka

**Comment by SSE4** [comment]
@tonka3000 you're right, probably something has changed in CPT. build was using testing channel, which was never uploaded to the bintray.
I've changed travis and appveyor to use correct environment variables to specify branch patterns explicitly: https://github.com/conan-community/conan-cmake-installer/commit/376fbf56b460a3701705cfd69c19110ee7a78da5

**Comment by tonka3000** [comment]
Hey @SSE4 ,

Is that really fixed with your commit? On bintray there is only cmake version up to 3.13 but f.e. 3.14 is not available.
I've look into appveyor log and for 3.14 it skip the upload with your latest fix.

I think your config is not right ...
```yml
CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
CONAN_CHANNEL: "stable"
CONAN_STABLE_BRANCH_PATTERN: "stable/*"
```
... because it only uploads when it has the stable branch pattern, but the latest code is on `master`, not on `stable/*`, so I think the correct config should be
```yml
CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
CONAN_CHANNEL: "stable"  #could also f.e. be "develop"
CONAN_STABLE_BRANCH_PATTERN: "master"
```

What do you think?

Greetings  
Tonka
